# -*- coding: utf-8 -*-
"""Questions & Answering pretrained model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSDCNPqBUMO-1bGrDfbvXyF_RiXLuAYy
"""

!pip install transformers

from transformers import pipeline

model_QA = pipeline("question-answering", model="deepset/roberta-base-squad2")

sentence = 'Enter you paragraph :NLP or Natural Language Processing is an AI field focused on computer-human language interaction. It aims to enable machines to understand, interpret, and generate human text meaningfully.Machine translation helps break language barriers between cultures. Virtual assistants like Siri and Alexa use advanced techniques to respond to voice commands. Sentiment analysis examines texts to identify positive or negative opinions.The evolution of large language models like GPT-4 and BERT continues to push boundaries in what machines can achieve with human language. Multimodal AI systems that combine text, audio, and visual processing are creating more comprehensive understanding capabilities. Ethical considerations around bias mitigation and responsible AI deployment are becoming increasingly important as these technologies become more integrated into daily life. The ongoing research in explainable AI aims to make NLP systems more transparent and trustworthy. '

questions = [
    "What does NLP aim to enable machines to do?",
    "What are examples of virtual assistants?",
    "What is sentiment analysis?",
    "What are large language models?"
]

for q in questions:
    answers = model_QA(question=q, context=sentence)
    print(f"{q}")
    print(f"{answers['answer']}")
    print(10*'*')